# Generated by Django 3.2 on 2021-05-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created',
            new_name='_created_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='_description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='keywords',
            new_name='_keywords',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated',
            new_name='_updated_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='gen_description',
        ),
    ]
