# Generated by Django 3.2 on 2021-05-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210516_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='_description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='_keywords',
        ),
        migrations.RemoveField(
            model_name='news',
            name='_meta_title',
        ),
        migrations.AddField(
            model_name='news',
            name='_meta_description',
            field=models.TextField(blank=True, verbose_name='HTML Page Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='_meta_keywords',
            field=models.CharField(blank=True, help_text='Optional keywords to be used in the HTML title tag. If left blank, the main keywords field will be used.', max_length=500, null=True, verbose_name='HTML Page Keywords'),
        ),
    ]
