# Generated by Django 3.2 on 2021-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='news/%Y%m%d/'),
        ),
    ]
