# Generated by Django 3.2.9 on 2021-12-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_url', models.ImageField(blank=True, upload_to='cases/')),
                ('detail', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': '成功案例',
                'verbose_name_plural': '成功案例',
            },
        ),
    ]
