# Generated by Django 3.2.6 on 2021-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcases',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='是否首页显示'),
        ),
        migrations.AlterField(
            model_name='ourcases',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='cases/', verbose_name='图片路径'),
        ),
    ]
