# Generated by Django 3.2.9 on 2021-12-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_ourcases_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourcases',
            options={'verbose_name': '成功案例', 'verbose_name_plural': '成功案例'},
        ),
    ]
