# Generated by Django 3.2.6 on 2021-12-27 14:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20211218_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcases',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
