# Generated by Django 3.2.9 on 2021-12-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_ourcases_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcases',
            name='img_url',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
