# Generated by Django 3.2.6 on 2021-09-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_date', models.DateTimeField(editable=False, null=True)),
                ('_updated_date', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='phone')),
                ('message', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'OnlineMessage',
                'verbose_name_plural': '在线留言',
            },
        ),
    ]
